### ISSUE TITLE
tabix error

### ISSUE THREAD

**Issue by kythol** [CCCKW/mHapTk#3]
Hi,

Thank you for the wonderful package. I have been having an issue running tanghulu command:

(mhaptools_py3.9) [root@cmp-pci-qa-02 meth_haplo]# mhaptk tanghulu --mhapPath SRX8208802.mhap.gz --cpgPath hg19_CpG.gz --region chr1:14435-14653 --outputFile test.data.tanghulu.pdf
Traceback (most recent call last):
  File "/root/anaconda3/envs/mhaptools_py3.9/bin/mhaptk", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/mhaptools_py3.9/lib/python3.9/site-packages/src/mhaptk.py", line 2438, in main
    M.tabixCPG(args.cpgPath, shift=500)
  File "/root/anaconda3/envs/mhaptools_py3.9/lib/python3.9/site-packages/src/mhaptk.py", line 1252, in tabixCPG
    records = tb.query(self.Chr, self.start - shift, self.end + shift)
tabix.TabixError: query failed

I'm having a hard time understanding the issue, and googling doesn't seem to help either. Sorry for bothering you

**Comment by kythol** [comment]
Ah my fault entirely, sorry. This error is not clear but I was actually missing index file for hg19_CpG.gz. It worked fine with it (just in case, tabix works with only bgzipped files).

Although this exact region from your example failed for me, another region worked fine. Thank again for your tool!
Lisa
